apiVersion: batch/v1
kind: Job
metadata:
  name: signoz-schema-migrator
  namespace: ms
spec:
  template:
    spec:
      containers:
      - name: signoz-schema-migrator
        image: signoz/signoz-schema-migrator:v0.129.12
        args: ["sync", "--dsn", "tcp://clickhouse:9000?username=otel&password=signoz"]
      restartPolicy: OnFailure
